Fix/prepare env
Ostorlab/py3chrome pull request #1
Opened 2023-03-17 08:44 UTC by 3asm

2023-03-17 08:53 UTC, najibraihan approved these changes

2023-03-17 10:51 UTC, deadly-panda requested changes, later dismissed

2023-03-17 10:51 UTC, deadly-panda commented on .github/workflows/pytest-linux.yml
> +        pip install .[agent]
These 2 lines are not needed in this project.
Apply this and the previous comment in the other workflow files too please.

2023-03-17 10:51 UTC, deadly-panda commented on .github/workflows/pytest-linux.yml
> +        git submodule update
Do we need this?

2023-03-17 13:09 UTC, 3asm commented on .github/workflows/pytest-linux.yml
> +        git submodule update
Good catch.

2023-03-18 11:19 UTC, deadly-panda commented
I do not see the submodule init&update removals?

2023-03-20 17:04 UTC, merged